[pytest]
testpaths = tests
python_files = test_*.py
norecursedirs =
    .git
    .pytest_cache
    .selenium-profiles
    .wdm
    __pycache__
    chrome-profile-*
    pytest-cache-files-*
addopts = -p no:cacheprovider
